name: Test Deployment
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-test.[0-9]+'
jobs:
  #
  # OneBlink Tenant
  #
  OneBlinkTest:
    name: Test Deployment (OneBlink)
    runs-on: ubuntu-latest
    environment: OneBlink Test
    env:
      TENANT: 'oneblink'
      ENVIRONMENT: 'test'
      PUBLIC_URL: https://oneblink-forms-test.cdn.oneblink.io
      ONEBLINK_ACCESS_KEY: ${{ secrets.ONEBLINK_ACCESS_KEY }}
      ONEBLINK_SECRET_KEY: ${{ secrets.ONEBLINK_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm install --global npm@11
      - run: npm ci
      - run: npm run build
      - run: npx oneblink cdn scope oneblink-forms.cdn.oneblink.io
      - run: npx oneblink cdn deploy dist --env test --force
  #
  # CivicPlus Tenant
  #
  CivicPlusTest:
    name: Test Deployment (CivicPlus)
    runs-on: ubuntu-latest
    environment: CivicPlus Test
    env:
      TENANT: 'civicplus'
      ENVIRONMENT: 'test'
      PUBLIC_URL: https://civicplus-forms-test.cdn.transform.civicplus.com
      ONEBLINK_ACCESS_KEY: ${{ secrets.ONEBLINK_ACCESS_KEY }}
      ONEBLINK_SECRET_KEY: ${{ secrets.ONEBLINK_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm install --global npm@11
      - run: npm ci
      - run: npm run build
      - run: npx civicplus cdn scope civicplus-forms.cdn.transform.civicplus.com
      - run: npx civicplus cdn deploy dist --env test --force
  #
  # OneBlink US Tenant
  #
  OneBlinkUSTest:
    name: Test Deployment (OneBlink US)
    runs-on: ubuntu-latest
    environment: OneBlink US Test
    env:
      TENANT: 'oneblinkUS'
      ENVIRONMENT: 'test'
      PUBLIC_URL: https://oneblink-forms-test.cdn.us.oneblink.io
      ONEBLINK_ACCESS_KEY: ${{ secrets.ONEBLINK_ACCESS_KEY }}
      ONEBLINK_SECRET_KEY: ${{ secrets.ONEBLINK_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm install --global npm@11
      - run: npm ci
      - run: npm run build
      - run: npx oneblink-us cdn scope oneblink-forms.cdn.us.oneblink.io
      - run: npx oneblink-us cdn deploy dist --env test --force
